// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Bay(arg1) {
  return window['go']['main']['Basic']['Bay'](arg1);
}

export function Change(arg1, arg2) {
  return window['go']['main']['Basic']['Change'](arg1, arg2);
}

export function FetchFromServer() {
  return window['go']['main']['Basic']['FetchFromServer']();
}

export function Flip(arg1, arg2) {
  return window['go']['main']['Basic']['Flip'](arg1, arg2);
}

export function GetImageFile() {
  return window['go']['main']['Basic']['GetImageFile']();
}

export function RemoveImage() {
  return window['go']['main']['Basic']['RemoveImage']();
}

export function SetImageFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['Basic']['SetImageFile'](arg1, arg2, arg3, arg4);
}
