// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Change(arg1:string,arg2:main.Cordinates):Promise<any>;

export function FetchFromServer():Promise<void>;

export function Flip(arg1:string,arg2:number,arg3:number,arg4:number):Promise<any>;

export function GetImageFile():Promise<any>;

export function RemoveImage():Promise<string>;

export function SetImageFile(arg1:number,arg2:number,arg3:number,arg4:number):Promise<string>;
