// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Initial() {
  return window['go']['main']['ShipStruct']['Initial']();
}

export function PlaceShip(arg1, arg2) {
  return window['go']['main']['ShipStruct']['PlaceShip'](arg1, arg2);
}

export function SetTime(arg1, arg2, arg3) {
  return window['go']['main']['ShipStruct']['SetTime'](arg1, arg2, arg3);
}
