// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Initial():Promise<any>;

export function PlaceShip(arg1:number,arg2:string):Promise<void>;

export function RemoveShip(arg1:string):Promise<void>;
